####################################################
############### General Parameters #################
####################################################
num_dim_x: 5
num_dim_u: 2
T: 10
dt: 0.1
platform: "cpu"

####################################################
########### Optimization Parameters ################
####################################################        
max_iter: 100
tol: 0.005

line_search_base: 0.1
line_search_a: 0
line_search_b: 3
line_search_c: 1

reg_min: 1e-5
reg_max: 1e8
reg_scale_down: 5
reg_scale_up: 5
reg_init: 1.0

max_attempt: 5

####################################################
############### Dynamics Parameters ################
####################################################
wheelbase: 0.257
width: 0.22
length: 0.40

delta_max: 0.35
delta_min: -0.35

v_max: 5.0
v_min: 0.0

omega_min: -6.0
omega_max: 6.0

a_max: 5.0
a_min: -5.0

v_ref: 1

####################################################
########## Parameters for ILQR COST ################
####################################################

########        State Cost          ############

# Path Offset Cost
dim_closest_pt_x: 0
dim_closest_pt_y: 1
dim_path_slope: 2
path_cost_type: 'quadratic'
path_weight: 4.0
path_huber_delta: 2

# Velocity Cost
vel_cost_type: 'quadratic'
vel_weight: 4.0
vel_huber_delta: 1

# Speed Limit Cost
dim_vel_limit: 3
vel_limit_a: 10.0
vel_limit_b: 1.0

# Heading Cost
heading_cost_type: 'quadratic'
heading_weight: 2
heading_huber_delta: 1

# Lateral Acceleration Cost
lat_accel_thres: 6.0
lat_accel_a: 5.0
lat_accel_b: 2.0

# Progress Cost
dim_progress: 4
progress_weight: 0

# Lane Boundary Cost
dim_right_boundary: 5
dim_left_boundary: 6
lane_boundary_a: 100.0
lane_boundary_b: 5.0

########        Control Cost          ############
ctrl_cost_type: 'quadratic'
ctrl_cost_accel_weight: 1.0
ctrl_cost_steer_weight: 0.5
ctrl_cost_accel_huber_delta: 1.0
ctrl_cost_steer_huber_delta: 1.0

########        Obstacle Cost          ############
obs_a: 25.0
obs_b: 10.0
